name: Build My First Game
on: push

jobs:
  build:
    name: ${{ matrix.platform.name }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'Linux (x64)'        ,os: ubuntu-20.04 }
          - { name: 'Windows (x64)'      ,os: windows-2022 }
          - { name: 'MacOS (Universal)'  ,os: macos-12 }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.24.x'

      - name: Use cmake
        run: cmake --version

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.name }}
          path: build/bin/*